# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=80)),
                ('app_key', models.CharField(max_length=80)),
                ('app_secret', models.CharField(max_length=80)),
                ('api_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=80)),
                ('remark', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=80)),
                ('tag_text', models.CharField(max_length=80)),
                ('tag_unit', models.CharField(blank=True, max_length=80)),
                ('tag_scale', models.IntegerField(default=1)),
                ('remark', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
